# (APPENDIX) Appendixes {-}

# Mitigation Strategies {#AppendixA}

While the analysis methodologies of the Highway Capacity Manual accommodate a wide range of geometric, traffic, and control characteristics, it generally does not provide specific warrants/guidelines for geometric and/or control characteristics revisions to implement to potentially address poor operational issues. Probably the most well-known example of this kind of guidance are the signal warrants provided in the Manual for Uniform Traffic Control Devices (MUTCD).

The purpose of this appendix is to help direct the analyst to resources that may help them determine appropriate strategies, particularly with respect to geometric and control characteristics, that will potentially result in improved operational conditions along rural highways. These resources are generally consist of published NCHRP project reports and peer-reviewed journal articles.

It is expected that the content in this appendix will be regularly updated when relevant publications become available. If you would like to make us aware of reference material that we should consider including in this section, please contact us as described in [Section 1.4.2](#ProvidingFeedback).


## General

The material listed in this section address rural highway issues more generally.

**Rural Transportation Issues: Research Roadmap [@NAP26343]**  
*Abstract: Although only 19% of the population live in rural areas, more than 70% of the U.S.'s four million miles of roadways are in rural areas. The rural transportation system also includes numerous airports; railways; inland and coastal waterways; rural and intercity buses; and bicycle, pedestrian, and multi-use paths and trails. In addition, approximately 47% of the nation\u2019s motor vehicle fatalities occur in rural areas.The TRB National Cooperative Highway Research Program's NCHRP Research Report 988: Rural Transportation Issues: Research Roadmap is designed to assist state departments of transportation and other public agencies and help inform policy-driven investment decisions.*

**America’s Rural Roads: Beautiful and Deadly**
*This report examines the extent of the safety problem on our nation’s rural roads. It discusses rural roads’ unique challenges and offers strategies to help SHSOs and their partners address behavioral highway safety issues.*  
https://www.ghsa.org/sites/default/files/2022-09/America%E2%80%99s%20Rural%20Roads%20-%20Beautiful%20and%20Deadly%20FNL.pdf


## Multilane Highways

***Accommodating turning movements***

**Criteria and Guidelines for Three-Lane Road Design and Operation [@DavisMNDOT]**  
*Abstract: A 4-3 conversion involves changing a four-lane undivided road into one with two general travel lanes separated by a two-way left turn lane. A commonly-used guideline states that a 4-3 conversion can be considering as long as the road’s average annual daily traffic (AADT) volume does not exceed 15,000 vehicles/day but opinions vary, from lowering the AADT threshold to 10,000 vehicles/day to anecdotal evidence for successful 4-3 conversions with AADTs as high as 20,000. The main objective of this project was to identify conditions where 4-3 conversions might be feasible at AADTs greater than 15,000. After reviewing the literature, we conducted simulation studies on three different roads to identify combinations of major and minor road flow where three-lane configurations provided acceptable levels of service. Eight intersections, with 16 approaches, were then selected to represent our findings. These results were presented as summary tables that practitioners could use to make initial assessments regarding 4-3 conversion feasibility.*


## Two-Lane Highways

***Passing Zones***

**Design Criteria for Minimum Passing Zone Lengths: Operational Efficiency and Safety Considerations [@Moreno2015]**  
*Abstract: Passing zones are provided to improve operational efficiency of two-lane highways where passes can be performed safely. Minimum passing zone lengths of 120 m were established in MUTCD and Green Book, although some studies indicate a potential need to increase them. However, no changes have been recommended pending further research on the safety of short passing zones. The objective of this study is to develop design and marking criteria for minimum passing zone lengths that consider traffic operational efficiency and safety. In the first part of this study, a traffic microsimulation was carried out with Aimsun software. The calibration and validation included the observation of 1,750 passing maneuvers in Spain. The results indicate that passing zones shorter than 250 m add very little to operational efficiency. In the second part of the study, a reliability analysis was applied. It quantified the probability that a passing maneuver was completed beyond the end of the passing zone (non-compliant passing maneuvers). Afterwards, the number of non-compliant passing maneuvers was calculated. Traffic flow as well as passing zone length were contributing factors. Findings from the analysis indicate that the minimum passing zone length should be increased to a minimum of 275 m, for high traffic volumes, 300 m for medium traffic volumes and 350 m for low traffic volumes. From this length, the number of non-compliant passing maneuvers decreases. The marginal increase in the minimum length of passing zones can potentially improve safety without significantly reducing the operational efficiency. The results can be directly used by practitioners to establish the minimum passing zone length based on the range of hourly volumes and the level of risk willing to assume.*

***Passing/Climbing Lanes***

The new two-lane highway analysis methodology chapter in the Highway Capacity Manual (7th edition) contains some guidance passing/climbing lanes. See Appendix A (Guidance on Optimizing Passing Lane Performance) of Chapter 15. More detail on some this content can be found in the following reference.

**Passing Lane Optimum Length on Two-Lane Highways [@Jafari2018]**  
*Abstract: An investigation into the optimum length of passing lanes on rural two-lane highways is presented in this paper. A passing lane is a short length of added lane to improve passing opportunities on two-lane two-way highways. The study utilized field data and traffic simulation in this investigation, with field data primarily used in calibrating and validating the traffic simulation program. A sensitivity analysis was conducted using traffic level and length of passing lane as the primary variables. The level of association between the reduction in platooning and study variables was examined. Study results showed that, within the range of passing lane length investigated in this study (0.5 mi to 3.0 mi), traffic performance continued to improve with the increase in passing lane length. Moreover, for the same target improvement in performance, the required passing lane length increases with the increase in traffic volume. The passing lane optimum lengths developed in this study all varied in the range between 0.80 and 2.0 miles depending on traffic volume.*

HCM Chapter 15 also contains calculations for determining the effective length of a passing lane (see Step 9 of the analysis methodology). Note that these calculations are included in the methodology described in this Guidebook.

HCM Chapter 15 also introduces some preliminary techniques for analyzing a 2+1 roadway configurations (also in Appendix) While this type of configuration is currently rare in the U.S., it has been successfully employed in many locations throughout Europe. Such a configuration can provide significant improvements to operations at a lower cost than converting to a multilane highway in some situations. 


## Intersections

A common location for operational hot-spots or slowdowns are intersections. The following references are focused on comparisons between different intersection configurations.

***Type of Control***

**Intersection Control Evaluation [Federal Highway Administration]**  
*Abstract: Intersection control evaluation (ICE) is a data–driven, performance–based framework to screen intersection alternatives and identify an optimal solution.*  
https://highways.dot.gov/safety/intersection-safety/ice


**NCHRP 17-98: Guide for Intersection Control Evaluation**  
*Abstract: A variety of intersection control evaluation processes and metrics are used by highway agencies for evaluating intersection geometry and control alternatives and identifying an optimal geometric and control solution for an intersection. These processes usually address safety, operational, multimodal, environmental, right-of-way, and cost impacts and other considerations. However, there is no widely accepted procedure or guide for evaluating new intersections or modifications to an intersection. The objective of this research was to develop a guide for intersection control evaluation. The guide includes associated processes and tools, in a format appropriate for consideration and adoption by the American Association of State Highway and Transportation Officials (AASHTO). For the purpose of this research intersections include interchanges.*  

This project was completed on 7/31/23 and publication materials are forthcoming. For the current status, see https://apps.trb.org/cmsfeed/TRBNetProjectDisplay.asp?ProjectID=4974


**Gray Areas in Isolated Intersection Control-Type Selection: Complementary Decision-Support Tool [@Bae2017]**  
*Abstract: The intersection control-type selections for future facilities can be determined by comparison of a common measure of effectiveness that is average control delay. However, rigid comparisons of such measures tend to mislead the decision-making process in practice, since there must be latent factors in quantification. To this end, this paper proposes the performance comparison framework of different transportation facility alternatives using a common quantitative measure. By considering the uncertainties in a quantification process, the proposed framework provides gray areas (i.e., intuitively visualized information, which decision-makers can use to assist in their engineering decisions). The average control delay of two-way stop control, all-way stop control, signal control types, and roundabouts were compared with contour lines of delay differences. It is found that the delay of a roundabout increases rapidly as the traffic demand increases. Hence, a signal control type has the minimum delay level in that case, despite the fact that the roundabout outperforms for most of the low-demand conditions. When the signal timing plan is optimized, this feature becomes evident. With consideration of the margin of error in the delay, a gray area on the minimum delay surface between the signal control and roundabout types enlarges in the low-demand area. The gray areas can be utilized by practitioners to decide the best intersection control type with consideration of construction and maintenance costs over delay reduction benefit.*

**Identifying the Adaptability of Different Control Types Based on Delay and Capacity for Isolated Intersection [@Danesh2023]**  
*Abstract: In urban road networks, intersections are the main bottlenecks. Selecting an appropriate intersection control type can significantly improve the performance of an isolated intersection. Therefore, this paper offers recommendations for selecting the most efficient control type among two-way stop control, signalized intersection (SIG), roundabout (RB), and signalized roundabout (SIGRB) based on capacity and delay. The procedure to calculate delay and capacity is taken from the Highway Capacity Manual 6th edition (2016), or developed separately if needed. Two flow patterns are assumed: fixed and time-varying demand. For fixed demand, the results show that SIGRB outperforms other control types both in capacity and delay at higher demand levels. It was also observed that increase in left-turn ratio increases the delay and decreases the capacity of all control types while its impact on SIGRB was the least. Considering time-varying demand, traffic volume fluctuates over the 5-h period of the analysis. It was found that using both RB and SIGRB together creates significantly less delay compared with the other options. Additionally, using RB provides less variability in delay when there is fluctuation in demand. The major finding of this research is that RB and SIGRB have potential benefits for delay in conditions of (i) high traffic volume, (ii) high left-turn ratio, and (iii) demand fluctuation. Furthermore, it is suggested that SIG should be used if the left-turn ratio is relatively low. The results of this study could help decision-makers to choose the best control type for an isolated intersection under various traffic conditions.*

**Comparison of Delays at Signal-Controlled Intersection and Roundabout [@Ištoka_Otković_Dadić_2012]**  
*Abstract: Delays belong to standard parameters used for the evaluation of any type of intersection and they are taken in the evaluation of the level of service of an intersection. Intersections with shorter delays bring about economical benefits both for the users and the community, and enable greater efficiency of a traffic system, which is becoming a significant criterion with the in-creasing motorization. The case studies carried out in Europe and worldwide reveal that roundabouts bring delay savings if compared with other intersections of the same operational level and nearly the same traffic volume. The paper shows the results of the comparison  analysis  of  the  roundabout  and  the  signal-controlled intersection in the city of Osijek, Croatia. The statistical indicators have given the basis for the evaluation of delays at the observed intersections, offering at the same time the possibility to compare the analysis conclusions on the local level with the conclusions of the case studies carried out throughout Europe and worldwide.*

**Comparing Roundabouts and Signalized Intersections Through Multiple-Model Simulation [@Zhou2022]**  
*Abstract: In modern transportation systems, more and more vehicles result in severe traffic congestion, affecting our daily life and modern logistics. Well-designed traffic infrastructures play an important role in implementing safe and efficient traffic systems. From subjective experience, roundabouts are more efficient than conventional signalized intersections because vehicles do not wait for traffic signals, decreasing which is the main reason for time-loss at signalized crossroads. This paper aims to further investigate the differences between intersections and roundabouts in the capacity of vehicle passing and other performance. Two scenarios with different traffic volumes are considered, including a large volume of traffic flow (2.44 vehicles per second) and a small volume of traffic flow (0.52 vehicles per second). In each scenario, we build six junction models including four intersections with different traffic light time and two roundabouts with different numbers of lanes. Multiple evaluation metrics (i.e., number of passing vehicles over time, mean speed of passing vehicles, mean number of halts per vehicle, mean time-loss per vehicle, and total time for all vehicles to pass) are considered to compare these models’ performance. Results illustrate that roundabouts have a higher capability of vehicle passing than intersections, especially for a large traffic volume. But roundabouts bring more halts per vehicle than signalized intersections when the traffic volume is large. When the volume of traffic flow is small, there is no significant efficiency difference between intersections and roundabouts. These results tend to be applied to future traffic junction designs to improve system efficiency.*

**Evaluating the Conversion of All-Way Stop-Controlled Intersections into Roundabouts [@Vlahos2008]**  
*Abstract: Roundabouts are becoming increasingly popular in the United States and have been considered for use at intersections facing operational or safety problems. A comparative analysis was performed on all-way stop-controlled (AWSC) intersections and roundabouts on the basis of aaSIDRA software after calibration against local conditions in Delaware and Maryland. A decision support system was developed in the form of a knowledge-based expert system on the basis of the results of the analysis to evaluate the performance of AWSC intersections and their potential success if converted into roundabouts. The results of the comparative analysis are in line with some previous researchers’ findings that AWSC intersections always perform worse than signal-controlled or roundabout type intersections under the same set of traffic conditions and geometric limitations.*

**Control-Type Selection at Isolated Intersections Based on Control Delay Under Various Demand Levels [@Han2008]**  
*Abstract: The Highway Capacity Manual (HCM 2000) displayed the figure Exhibit 10-15 for the purpose of forecasting the likely intersection control types for future facilities. Because this figure is from a source external to HCM, to verify it, this paper employs HCM methodologies for the estimation and comparison of control delay, the choice measure of effectiveness at intersections controlled by signal, all-way stop signs, and two-way stop signs. After detailed analyses of more than 5,000 cases using Highway Capacity Software, results of control delay with various control types under a wide range of demand conditions were charted for comparison with Exhibit 10-15. It is found that Exhibit 10-15 is inconsistent with the results from HCM methodologies and, perhaps, should be replaced with the figures developed in this paper. On the basis of the criterion of minimizing delay alone, it is found that if demand is unbalanced between major and minor streets and if the traffic is low on minor streets, two-way-stop control should be used; if demand is somewhat balanced and minor streets see low to medium traffic, all-way-stop control is preferred; otherwise, signal control should be favored. The paper also demonstrates that the percentage of left-turning traffic has a significant effect on decisions involving intersection control types.*

**Effects of Approach Speed at Rural High-Speed Intersections: Roundabouts Versus Two-Way-Stop Control [@Isebrands2014]**  
*Abstract: Speed can increase the risk of injury-producing crashes, especially at intersections where vehicles may be approaching and entering the intersection with high speed differentials. It is known that roundabouts force all drivers to reduce their speed in the intersection; however, speed data in advance of the roundabout approach were not available for roundabouts with high-speed approaches to verify this phenomenon. In this research, a comparative evaluation of the difference in the average approach speeds between rural roundabouts and rural two-way-stop-controlled intersections and between rural roundabouts with and without rumble strips on the intersection approaches was performed. Approach speed data proved that drivers could slow down in advance of roundabouts on rural roadways. The mean speed 100 ft from the yield line of the roundabouts was 2.5 mph lower than the mean speed 100 ft from the stop bar at stop-controlled approaches. Additionally, a comparison of roundabout approaches with and without rumble strips showed mean speeds 4.3 and 3.3 mph lower 100 and 250 ft from the yield line, respectively, for approaches with rumble strips; however, the variation in speeds increased with the introduction of rumble strips.*


***Turn/Auxillary Lanes***

There have been several NCHRP-funded projects that examined driveway and turn lane design issues for highway corridors; however, these studies are generally focused on geometric design and safety elements. Operational issues are largely discussed only in qualitative terms. A brief summary of these studies follows.

@NCHRPRep457 developed an engineering study guide for evaluating intersection improvements, as part of NCHRP Project 3-58. The objectives of the guide are “(1) to define the steps involved in an engineering study of a problem intersection and (2) to provide guidelines for using capacity analysis or simulation to determine the most effective alternative on the basis of operational considerations.” This guide provides several warrants to assist with identifying when turn lanes may be appropriate, and if so, how much storage they should provide. Warrants are also provided to assist in identifying the appropriate type of intersection (signalized, stop controlled, roundabout).

@NAP22296 examined design guidance for intersection auxiliary lanes. This work was performed under NCHRP Project 3-102. The results of this project expand on guidance provided in the AASHTO Green Book and highlights information regarding bypass lanes, channelized right-turn lanes, deceleration and taper length, design and capacity of multiple left-turn lanes, and alternative intersection designs.

@NAP22608 developed guidance for the selection and design of left-turn accommodations at unsignalized intersections, as part of NCHRP Project 3-91. The report includes 11 case studies of typical situations that illustrate the use of the guidance. 

@NAP14399 developed a design guide as a by-product of the research for NCHRP Project 15-35, “Geometric Design of Driveways.” This guide provides recommendations for the geometric design of driveways that consider standard engineering practice and accessibility needs and provide for safe and efficient travel on the affected roadway. The research included a literature review, a survey of street and highway departments, and field studies leading to an improved understanding of the state of the practice. This guide presents changes to that state of practice based on the evolving requirements for driveways.
  The report includes driveway-related terms and definitions, an examination of basic geometric controls, a summary of access spacing principles, and detailed discussions of various geometric design elements. This publication complements documents such as the AASHTO Policy on the Geometric Design of Streets and Highways and the Access Management Manual. This guide is intended for use in both the public and private sectors.

@KikuchiChakroborty examined warrant criteria for justifying a left-turn lane on a major two-lane roadway that intersects a minor roadway, in a ‘T’ configuration. Three criteria were considered: (a) probability that one or more waiting through vehicles are present on the approach; (b) delay (average delay to the "caught" through vehicles, average delay to all through vehicles, and delay savings due to the left-turn lane); and (c) degradation of the level of service. Volume combinations (through, left-turn, and opposing flow) that would justify a left-turn lane under each of the criteria are presented.


## Arterials

**Access Management Manual [@TRBAccessManagement]**  
*Abstract: TRB’s Access Management Manual,second edition, provides guidance on a coordinated approach to transportation and community design that is designed to help enhance mobility, provide greater mode choice, and improve environmental quality. The content is interdisciplinary, with guidance pertinent to various levels of government as well as to pedestrians, bicyclists, and motorized vehicles, including trucks and buses. Access management is addressed comprehensively, as a critical part of network and land use planning.*


**Evaluating the Performance of Corridors with Roundabouts [@NAP22348]**  
*Abstract: TRB's National Cooperative Highway Research Program (NCHRP) Report 772: Evaluating the Performance of Corridors with Roundabouts provides measurement and evaluation methods for comparing the performance of a corridor with a functionally interdependent series of roundabouts to a corridor with signalized intersections in order to arrive at a design solution.For the purposes of this research, a series of roundabouts is defined as at least three roundabouts that function interdependently on an arterial.*
