--- 
title: ""
subtitle: ""
author: ""
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
geometry: "left=2.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm"
bibliography: [RefsOther.bib, RefsMitigation.bib, RefsBicycle.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo:
description: "This document provides guidance on applying the Highway Capacity Manual and probe vehicle data analysis methodologies to rural highways. Rural highways are comprised of contiguous segments of multilane highway, two-lane highways, intersections (signalized, roundabout, stop control), and arterials through rural towns."
version: 1.0
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if("kableExtra" %in% rownames(installed.packages()) == FALSE) {install.packages("kableExtra")} 
library(kableExtra)

TableColumnHeaderTextAngle = 0
if (knitr::is_latex_output() == TRUE){
  TableColumnHeaderTextAngle = 90
}
```






```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(.packages(), 'bookdown', 'knitr', 'rmarkdown'), 'packages.bib')
```


```{r eval=FALSE, include=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```

